AWSTemplateFormatVersion: "2010-09-09"
Description: Full Auto Scaling Apache EC2 Stack with ALB and EC2 Key Pair via CloudFormation

Resources:

  ApacheKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: apache-key
      KeyType: rsa
      Tags:
        - Key: Name
          Value: apache-key

  ApacheSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and SSH
      VpcId: vpc-05b9fc4f0c956d7b8
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  ApacheLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: apache-template
      LaunchTemplateData:
        ImageId: ami-084568db4383264d4
        InstanceType: t2.micro
        KeyName: !Ref ApacheKeyPair
        SecurityGroupIds:
          - !Ref ApacheSecurityGroup
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            apt update -y
            apt install apache2 -y
            systemctl enable apache2
            systemctl start apache2

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP to ALB
      VpcId: vpc-05b9fc4f0c956d7b8
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: apache-alb
      Subnets:
        - subnet-03f8e36839a263ab8
        - subnet-07d4bee4e0b3a37d7
      SecurityGroups:
        - !Ref ALBSecurityGroup
      Scheme: internet-facing
      Type: application

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: apache-targets
      Port: 80
      Protocol: HTTP
      VpcId: vpc-05b9fc4f0c956d7b8
      TargetType: instance
      HealthCheckPath: /

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MinSize: '1'
      MaxSize: '2'
      DesiredCapacity: '1'
      VPCZoneIdentifier:
        - subnet-03f8e36839a263ab8
        - subnet-07d4bee4e0b3a37d7
      TargetGroupARNs:
        - !Ref ALBTargetGroup
      LaunchTemplate:
        LaunchTemplateId: !Ref ApacheLaunchTemplate
        Version: !GetAtt ApacheLaunchTemplate.LatestVersionNumber
      Tags:
        - Key: Name
          Value: apache-autoscaling
          PropagateAtLaunch: true

Outputs:
  LoadBalancerDNS:
    Description: DNS name of the Application Load Balancer
    Value: !GetAtt ApplicationLoadBalancer.DNSName
